### ISSUE TITLE
Connect through SSH tunnel

### ISSUE THREAD

**Issue by ujovlado** [keboola/mongodb-extractor#2]

**Comment by Halama** [comment]
Možná by bylo dobrý v rámci toho zkusit jestli by se na ten ssh tunel nedala přidat podpora přímo do docker bundle https://keboola.productboard.com/feature-board/planning/features/57245 Nebo by to minimálně mohla být nějaká composer knihovna která by se sdílela v komponentách. Teď je to implementovaný zřejmě tady https://github.com/keboola/db-extractor-common a používají to z toho odvozené extraktory.
