### ISSUE TITLE
getName() on null 

### ISSUE THREAD

**Issue by odinuv** [keboola/mongodb-extractor#53]
Fatal error: Uncaught Error: Call to a member function getName() on null in \/code\/src\/Keboola\/MongoDbExtractor\/Parser\/Mapping.php:54\nStack trace:\n#0 \/code\/src\/Keboola\/MongoDbExtractor\/Export.php(94): Keboola\\MongoDbExtractor\\Parser\\Mapping->parse(Array)\n#1 \/code\/src\/Keboola\/MongoDbExtractor\/Extractor.php(97): Keboola\\MongoDbExtractor\\Export->parseAndCreateManifest()\n#2 \/code\/src\/Keboola\/MongoDbExtractor\/Application.php(37): Keboola\\MongoDbExtractor\\Extractor->extract('\/data\/out\/table...')\n#3 \/code\/src\/run.php(40): Keboola\\MongoDbExtractor\\Application->actionRun('\/data\/out\/table...')\n#4 {main}\n  thrown in \/code\/src\/Keboola\/MongoDbExtractor\/Parser\/Mapping.php on line 5

https://keboola.slack.com/archives/docker-notifications/p1485870100000029

**Comment by ujovlado** [comment]
Fixed in #51

**Comment by odinuv** [comment]
Aha, tak sorry :) Mas to napsat do #docker-notifications :)
