### ISSUE TITLE
Internal error: Argument 1 passed to Raw::writerRowToOutputFile() must be an object, null given

### ISSUE THREAD

**Issue by kacurez** [keboola/mongodb-extractor#92]
message: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-mongodb:v1.11.0 container '502728559-502728560--0-keboola-ex-mongodb' failed: (2) [2019-05-07 18:36:17] app-errors.ERROR: Argument 1 passed to Keboola\MongoDbExtractor\Parser\Raw::writerRowToOutputFile() must be an object, null given, called in /code/src/Keboola/MongoDbExtractor/Parser/Raw.php on line 50 {"class":"TypeError","trace":"#0 /code/src/Keboola/MongoDbExtractor/Parser/Raw.php(50): Keboola\\MongoDbExtractor\\Parser\\Raw->writerRowToOutputFile(NULL)\n#1 /code/src/Keboola/MongoDbExtractor/Export.php(101): Keboola\\MongoDbExtractor\\Parser\\Raw->parse(Array)\n#2 /code/src/Keboola/MongoDbExtractor/Extractor.php(112): Keboola\\MongoDbExtractor\\Export->parseAndCreateManifest()\n#3 /code/src/Keboola/MongoDbExtractor/Application.php(39): Keboola\\MongoDbExtractor\\Extractor->extract('/data/out/table...')\n#4 /code/src/run.php(50): Keboola\\MongoDbExtractor\\Application->actionRun('/data/out/table...')\n#5 {main}"} []

https://papertrailapp.com/events?q=fd82dfaa4ad8bf79d29c70027999abfa

**Comment by kacurez** [comment]
posledne 3 dni sa to opakuje celkom pravidelne napr zase tu
https://keboola.slack.com/archives/C09U3R1J4/p1557494351103600

**Comment by ujovlado** [comment]
Pozrem to cez vikend.

**Comment by kacurez** [comment]
ok pozri na ten PR co som pripravil ci to nahodou nefixne https://github.com/keboola/mongodb-extractor/pull/93 :)

**Comment by ujovlado** [comment]
Pravdepodobne sa tam dostali nejake data, ktore sa nepodarilo decodovat. Je tam len klasicky `json_decode`, pretoze sa spolieham, ze `mongoexport` dava ten json validny.

Zmenim `json_decode` sa "serializer->decode" zo symfony alebo z nette/utils, nech to vidime.

Potom sa rozhodnem, co s tym riadkom.

**Comment by ujovlado** [comment]
V #94 som poriesil ten error handling, uz to skonci spravnym aplikacnym errorom. Je to teda chyba vystupu z mongoexport asi. 

V #95 tam pridam logovanie a skusim to znovu. Nedari sa mi to nasimulovat lokalne. Zatial to zaloguje a skonci app errorom.

**Comment by ujovlado** [comment]
Takze je to tym, ze niekde v tom dokumenta maju `NaN` ... lezie to z `mongoexport`.

![Screenshot_2019-05-12_15-21-47](https://user-images.githubusercontent.com/419849/57582823-c5f61c80-74c9-11e9-9532-4c5f8726b725.png)

Nebudem to replacovat alebo tak, taketo dokumenty preskocime a zalogujeme do eventov.

**Comment by kacurez** [comment]
aha, nebolo by lepsie to ulozit ako prazdny string?

**Comment by ujovlado** [comment]
No my to tak neukladame. Takto to je vyexportovane z mongoexport. Je to JSON, no je nevalidny prave kvoli tomu `NaN`. Nechcem to asi replacovat alebo tak.

**Comment by kacurez** [comment]
ok tak ja im napisem nech si opravia data. 
btw nemohla by to byt user error? Takto to vypada ze chyba je u nas :)

**Comment by ujovlado** [comment]
Este to nie je opravene. ;)

**Comment by kacurez** [comment]
aha ok sorry som to nedostatocne precital, uz vidim ze tie data chces len zalogovat a preskocit.
